ecommerce_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'airflow') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'airflow') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'ecommerce') }}"
      schema: staging
      threads: 2
